### ISSUE TITLE
 Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available

### ISSUE THREAD

**Issue by laapsaap** [MagerValp/AutoDMG#211] opened 2018-04-08 19:21 UTC
## Description of issue

When building AutoDMG image sometimes it idles for a few hours before continuing. 

Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available

It doesnt seem to always happen, but once every few runs.

## Steps to reproduce

Running the AutoDMG cli to create an image, everything is cached

## Log file

```
00:44:33 progress: 71.7%
02:44:57 progress: 71.9%2018-04-06 04:44:55.045 Python[8809:66695] Couldn't decode <4945443a 4d53473a 556e6d6f 756e7469 6e672027 2f566f6c 756d6573 2f4d6163 696e746f 73682048 44272066 61696c65 642c2066 6f726365 20617474 656d7074 2080a60a> as UTF-8
04:45:21 2018-04-06 06:45:13.533 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.533 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.533 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.533 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.534 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.534 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.534 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.534 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.537 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.537 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.537 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.537 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.537 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.537 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.538 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.538 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
04:45:21 2018-04-06 06:45:13.538 Python[8809:66695] Socket at /tmp/se.gu.it.IEDSocketListener.d12e8bbdda1e3e63 failed: [Errno 55] No buffer space available
04:45:21 2018-04-06 06:45:13.538 Python[8809:66695] Failed socket message: <62706c69 73743030 d2010203 04566163 74696f6e 57706572 63656e74 5f100f75 70646174 655f7072 6f677265 73732340 23e02ff8 ec0f8808 0d141c2e 00000000 00000101 00000000 00000005 00000000 00000000 00000000 00000037>
06:46:59 
06:46:59 progress: 72.0%
06:46:59 progress: 72.1%
```

**Comment by MagerValp** [comment] 2018-04-09 05:40
Could you please attach the full debug log? I need to see the context to determine how this error happens.

**Comment by laapsaap** [comment] 2018-06-28 10:31
It has been some time ago that I was working on this, if it happens again I will attach the logs thanks.

**Comment by MagerValp** [comment] 2018-08-11 09:27
Closing this as a likely dupe of #169

**Closed by MagerValp** 2018-08-11 09:27 UTC
