### ISSUE TITLE
High Sierra 10.13.4

### ISSUE THREAD

**Issue by cattleman1** [MagerValp/AutoDMG#210] opened 2018-04-02 15:03 UTC
## Description of issue
Recently updated to 10.13.4 on a test system to want to build a new 10.13.4 install.  Created this today.  AutoDMG keeps crashing with the following errors.

[AutoDMG 2018-04-02 09.50.log](https://github.com/MagerValp/AutoDMG/files/1868383/AutoDMG.2018-04-02.09.50.log)
ave the debug log and attach it by dragging it here)_

**Comment by MagerValp** [comment] 2018-04-02 16:08
Closing as duplicate of #209

**Closed by MagerValp** 2018-04-02 16:08 UTC
Labels: duplicate
