### ISSUE TITLE
Applying All Updates changes Yosemite 10.10.5 build from 14F27 to 14F1509

### ISSUE THREAD

**Issue by apizz** [MagerValp/AutoDMG#141] opened 2015-12-30 19:16 UTC
When attempting to build a 10.10.5 image and apply all available updates, get an unknown build when I drag the built image back into AutoDMG.  Doesn't appear the built image is bootable when applied to a test machine.

**Comment by MagerValp** [comment] 2016-01-02 10:06
Duplicate of issue #129, merging them.

**Closed by MagerValp** 2016-01-02 10:06 UTC
